#!/bin/sh

set -o errexit
set -o xtrace

# test a docker process
docker ps | grep -q caddy-gen

# test availability and status code
# TODO test virtual.host label feature

# test feature CADDY_TEMPLATE
docker exec caddy-gen sh -c "printf 'http://test-template.localhost {\nrespond \"template\"\n}\n' > /tmp/template.tmpl"
docker exec caddy-gen sh -c 'export CADDY_TEMPLATE=/tmp/template.tmpl && sh /code/docker-entrypoint.sh'
sleep 2
test "$(curl 0.0.0.0:80 -s -H 'Host: test-template.localhost')" = 'template'

# test feature CADDY_SNIPPET
docker exec caddy-gen sh -c "printf 'http://test-snippet.localhost {\nrespond \"snippet\"\n}\n' > /tmp/snippet.tmpl"
docker exec caddy-gen sh \
  -c 'export CADDY_TEMPLATE=/tmp/template.tmpl CADDY_SNIPPET=/tmp/snippet.tmpl && sh /code/docker-entrypoint.sh'
sleep 2
test "$(curl 0.0.0.0:80 -s -H 'Host: test-template.localhost')" = 'template'
test "$(curl 0.0.0.0:80 -s -H 'Host: test-snippet.localhost')" = 'snippet'
