language: python

python:
  - 3.6

services:
  - docker

install:
  - bash test/setup

script:
  - sleep 5 # wait for container to start
  - bash test/run

notifications:
  email:
    on_success: never
    on_failure: change
